name: Build docker image
on:
  push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        distribution: 'graalvm'
        java-version: '23'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image-musl: true
    - name: Build Java
      run: javac Main.java
    - name: Build image
      run: native-image --static --libc=musl --gc=epsilon -march=compatibility -Os --native-compiler-options="-Wl,--strip-all" Main
    - name: Install UPX
      uses: crazy-max/ghaction-upx@v2
      with:
        install-only: true
    - name: compress
      run: upx --lzma --best -o main-compressed main
    - name: Create Docker image
      run: docker build -t dan1st/hello-world-native-java .
    - name: Inspect
      run: docker inspect dan1st/hello-world-native-java
    - name: Run
      run: docker run dan1st/hello-world-native-java
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: dan1st
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/master'
      run: docker push dan1st/hello-world-native-java
     
